### ISSUE TITLE
[BUG] Can't see loot info when something is behind the roll frame

### ISSUE THREAD

**Issue by RustamTastimullin** [Karl-HeinzSchneider/WoW-DragonflightUI#531]
**Describe the bug**
When roll frame pops i can't see loot info by mouseovering if there is something behind the roll frame.
If i move somewhere away from anything (like npc) that behind the roll frame - then i could see loot info again by mouseover in roll frame.

**Versions (please complete the following information):**
 - WoW: [MOP classic(eu)]
 - Addon [v0.33.7]

**Additional context**

**Comment by RustamTastimullin** [comment]
Yes, you understand correctly!

![Image](https://github.com/user-attachments/assets/685ac29c-5080-4229-b8c2-1a325f3f22c0)

**Comment by Karl-HeinzSchneider** [comment]
Logically the issue doesnt really make sense, but its also like that when using another addon to move the loot container.
But should be fixed with a32ffa942328f45926b494348abec2b1aea5bc96, 

![Image](https://github.com/user-attachments/assets/1ce463ba-3866-452d-bfde-1a60cb78b7fe)

Thanks for the report!

**Comment by RustamTastimullin** [comment]
Tryed locally this fix and here the result:

Still can't see loot info when smthng is behide roll frame
